env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

stable_test_task:
  name: "Rust Stable"
  container:
    image: rust:latest
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  setup_script:
    - rustup component add rustfmt
  primary_test_script:
    - rustc --version
    - cargo test --all
  backtrace_shim_test_script:
    - cargo test --manifest-path compatibility-tests/backtrace-shim/Cargo.toml
  backtraces_impl_backtrace_crate_test_script:
    - cargo test --manifest-path compatibility-tests/backtraces-impl-backtrace-crate/Cargo.toml
  futures_0.1_test_script:
    - cargo test --manifest-path compatibility-tests/futures-0.1/Cargo.toml
  context_selectors_have_documentation_test_script:
    - cargo test --manifest-path compatibility-tests/context-selectors-have-documentation/Cargo.toml
  renamed_import_test_script:
    - cargo test --manifest-path compatibility-tests/renamed-import/Cargo.toml
  compile_fail_test_script:
    - cargo test --manifest-path compatibility-tests/compile-fail/Cargo.toml
  lint_script:
    - >
      for i in $(find . -name 'Cargo.toml'); do
        pushd $(dirname $i);
        cargo +stable fmt --all -- --check;
        popd;
      done
  before_cache_script: rm -rf $CARGO_HOME/registry/index

doc_test_task:
  name: "Docs"
  env:
    # unused-braces is due to https://github.com/rust-lang/rust/issues/70717
    RUSTFLAGS: "-D warnings -A unused-braces"
    RUSTDOCFLAGS: "${RUSTFLAGS}"
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  version_information_script:
    - rustc +nightly --version
  docs_script:
    - cargo +nightly doc
  backtraces_docs_script:
    - cargo +nightly doc --features=backtraces
  backtraces_impl_backtrace_crate_docs_script:
    - cargo +nightly doc --features=backtraces-impl-backtrace-crate
  unstable_backtraces_impl_std_docs_script:
    - cargo +nightly doc --features=unstable-backtraces-impl-std
  futures_01_docs_script:
    - cargo +nightly doc --features=futures-01
  futures_docs_script:
    - cargo +nightly doc --features=futures
  before_cache_script: rm -rf $CARGO_HOME/registry/index

doc_tests_task:
  name: "Documentation Tests"
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 4Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  version_information_script:
    - rustc +nightly --version
  backtraces_doctests_script:
    - cargo +nightly test --doc --features=backtraces
  backtraces_impl_backtrace_crate_doctests_script:
    - cargo +nightly test --doc --features=backtraces-impl-backtrace-crate
  # Disabled because every doctest would need to enable the feature
  # from the standard library too.
  #
  # unstable_backtraces_impl_std_doctests_script:
  #   - cargo +nightly test --doc --features=unstable-backtraces-impl-std
  futures_01_doctests_script:
    - cargo +nightly test --doc --features=futures-01
  futures_doctests_script:
    - cargo +nightly test --doc --features=futures,internal-dev-dependencies
  before_cache_script: rm -rf $CARGO_HOME/registry/index

no_std_test_task:
  name: "Rust Stable (no_std)"
  container:
    image: rust:latest
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  setup_script:
    - rustup target add thumbv6m-none-eabi
  primary_test_script:
    - rustc --version
    - cargo build --no-default-features --target thumbv6m-none-eabi
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_test_task:
  name: "Rust Nightly"
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - rustc +nightly --version
    - cargo +nightly test
  std_backtrace_test_script:
    - RUST_BACKTRACE=1 cargo +nightly test --manifest-path compatibility-tests/backtraces-impl-std/Cargo.toml
  minimum_version_test_script:
    - cargo +nightly -Z minimal-versions update
    # These versions determined by trial and error
    - cargo +nightly update -p backtrace-sys --precise 0.1.20
    - cargo +nightly update -p libc:0.2.0 --precise 0.2.7
    - cargo +nightly test
  futures_test_script:
    - cd compatibility-tests/futures/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

v1_34_test_task:
  name: "Rust 1.34"
  container:
    image: rust:1.34
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - cd compatibility-tests/v1_34/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

v1_31_test_task:
  name: "Rust 1.31"
  container:
    image: rust:1.31
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - cd compatibility-tests/v1_31/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
