[package]
name = "snafu-derive"
version = "0.7.0-beta.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

description = "An ergonomic error handling library"
documentation = "https://docs.rs/snafu"
repository = "https://github.com/shepmaster/snafu"

license = "MIT OR Apache-2.0"

[features]
unstable-backtraces-impl-std = []

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.3.3"
